health check and staging

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -13,6 +13,11 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v4
 
+    - name: Set version tag
+      run: |
+        VERSION=v${{ github.run_number }}
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
+
     - name: Azure Login
       uses: azure/login@v2
       with:
@@ -25,22 +30,40 @@ jobs:
         username: ${{ secrets.ACR_USERNAME }}
         password: ${{ secrets.ACR_PASSWORD }}
   
-
-    - name: Build Docker image (amd64)
+    - name: Build Docker image
       run: |
         IMAGE_TAG=${{ github.sha }}
-        docker build --platform linux/amd64 -f app/azure/api/Dockerfile -t ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG .
+        docker build --platform linux/amd64 \
+          -t ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG \
+          -t ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:${{ env.VERSION }} \
+          ./app/azure/api
 
     - name: Push image to ACR
       run: |
         IMAGE_TAG=${{ github.sha }}
         docker push ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG
+        docker push ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:${{ env.VERSION }
 
-    - name: Deploy to Azure Container Apps
+    # 🚀 Deploy to STAGING (change here)
+    - name: Deploy to staging
       run: |
         IMAGE_TAG=${{ github.sha }}
         az containerapp update \
-          --name ${{ secrets.CONTAINERAPP_NAME }} \
+          --name job-api-staging \
           --resource-group ${{ secrets.RESOURCE_GROUP }} \
           --image ${{ secrets.ACR_LOGIN_SERVER }}/job-aggregator-api:$IMAGE_TAG
+
+     # ⏳ Wait
+    - name: Wait for app to start
+      run: sleep 20
+
+     # ❤️ Health check
+    - name: Health check
+      run: |
+        STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://<staging-url>/health)
+        if [ "$STATUS" -ne 200 ]; then
+          echo "Health check failed"
+          exit 1
+        fi
+
 
